const FFall = [
  {
    code: "URM 111",
    name: "Human Rights",
    level: 1,
    semester: 1,
    program: "general",
    credit_hours: "1",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
    
  },
  {
    code: "URM 112",
    name: "Introduction to Computers",
    level: 1,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "BSM 113",
    name: "English Language (1)",
    level: 1,
    semester: 1,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "BSM 114",
    name: "Physics",
    level: 1,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "BSM 115",
    name: "Fund of Manage & Economics",
    level: 1,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "BSM 116",
    name: "Mathematics (1)",
    level: 1,
    semester: 1,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "CSM 117",
    name: "Introduction to Programming",
    level: 1,
    semester: 1,
    program: "general",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
];


const FSpring = [
  {
    code: "URM 121",
    name: "Entrepreneurship & Innovation",
    level: 1,
    semester: 2,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
    
  },
  {
    code: "URM 122",
    name: "Marketing & Digital Strategy",
    level: 1,
    semester: 2,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "BSM 123",
    name: "Discrete Math & Graph",
    level: 1,
    semester: 2,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "BSM 124",
    name: "English Language (2)",
    level: 1,
    semester: 2,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "BSM 125",
    name: "Digital Systems",
    level: 1,
    semester: 2,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "BSM 126",
    name: "Mathematics (2)",
    level: 1,
    semester: 2,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "CSM 127",
    name: "Object Oriented Programming",
    level: 1,
    semester: 2,
    program: "general",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
];

const SFall = [
  {
    code: "URM 211",
    name: "Natural Res & Sustainability",
    level: 2,
    semester: 1,
    program: "general",
    credit_hours: "1",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
    
  },
  {
    code: "BSM 212",
    name: "Electronics ",
    level: 2,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "BSM 213",
    name: "Project Manage Professional",
    level: 2,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "BSM 214",
    name: "Probability & Statistic",
    level: 2,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "CSM 215",
    name: "Microprocessors",
    level: 2,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "CSM 216",
    name: "Data Structures",
    level: 2,
    semester: 1,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },

];
const SSpring = [
  {
    code: "URM 221",
    name: "Creative & Scientific Thinking",
    level: 2,
    semester: 2,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
    
  },

  {
    code: "BSM 222 ",
    name: "Mathematics (3)",
    level: 2,
    semester: 2,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },

  {
    code: "CSM 223",
    name: "Visual Programming",
    level: 2,
    semester: 2,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },

  {
    code: "CSM ",
    name: "Computer Architecture",
    level: 2,
    semester: 2,
    program: "general",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },

  {
    code: "CSM 225",
    name: "Computer Security",
    level: 2,
    semester: 2,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },

  {
    code: "ISM 226",
    name: "Database Management Systems (1)",
    level: 2,
    semester: 2,
    program: "general",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },

];

const TFall = [
  // Genreal
  {
    code: "CSM 311",
    name: "Operating Systems",
    level: 3,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",

    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
    
  },
  {
    code: "ISM 312",
    name: "Operations Research (1)",
    level: 3,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "NTM 313",
    name: "Computer Networks",
    level: 3,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "CSM 314",
    name: "Software Engineering (1)",
    level: 3,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "AIM 315",
    name: "Artificial Intelligence",
    level: 3,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  // CS 
  {
    code: "CSE 316",
    name: "Computer Science Elective (1)",
    level: 3,
    semester: 1,
    program: "CS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  // IS
  {
    name: "Systems Analysis and Design",
    code: "ISM 314",
    level: 3,
    semester: 1,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    name: "Information Systems",
    code: "ISM 315",
    level: 3,
    semester: 1,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "ISE 316",
    name: "nformation Systems Elective (1)",
    level: 3,
    semester: 1,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  //AI
  {
    code: "AIE 316",
    name: "Artificial Intelligence Elective (1)    ",
    level: 3,
    semester: 1,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },

  //Network Technologies
  {
    code: "NTM 315",
    name: "Optical Network",
    level: 3,
    semester: 1,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "NTE 316",
    name: " Networking Technologies Elective (1)",
    level: 3,
    semester: 1,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },


];

const TSpring = [
  // Genreal
  {
    code: "URM 321",
    name: "Research Methods & Ethics",
    level: 3,
    semester: 2,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",

    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
    
  },
  {
    code: "CSM 323",
    name: "Distributed Comp Sys",
    level: 3,
    semester: 2,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "CSM 324",
    name: "Computer Graphics",
    level: 3,
    semester: 2,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },


  // CS 
  {
    code: "CSM 326",
    name: "Computer Science Elective (2)",
    level: 3,
    semester: 2,
    program: "CS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "CSM 322",
    name: "Theory of Compilers",
    level: 3,
    semester: 2,
    program: "CS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "CSM 325",
    name: "Theory of Algorithms",
    level: 3,
    semester: 2,
    program: "CS",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },

  // IS
  {
    name: "Operations Research (2)",
    code: "ISM 322",
    level: 3,
    semester: 2,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "20",
    byLaw: "2",
  },
  {
    name: "ISM 325",
    code: "Modeling and Simulation",
    level: 3,
    semester:2,
    program: "IS",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    name: "ISM 324",
    code: "Information Retrieval",
    level: 3,
    semester:2,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },


  //AI
  {
    code: "AIE 322",
    name: "Image Proc & Pattern Recognition",
    level: 3,
    semester: 2,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "AIM 323",
    name: "Programming for AI",
    level: 3,
    semester: 2,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "AIM 325",
    name: "Fundamentals of Data Science",
    level: 3,
    semester: 2,
    program: "AI",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "AIE 326",
    name: "Artificial Intelligence Elective (2)    ",
    level: 3,
    semester: 2,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },

  //Network Technologies
  {
    code: "NTM 322",
    name: "Network Automation"    ,
    level: 3,
    semester: 2,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "NTE 324",
    name: "Cybersecurity",
    level: 3,
    semester: 2,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "NTM 325",
    name: "Routing and switching",
    level: 3,
    semester: 2,
    program: "NT",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "NTM 326",
    name: "Networking Technologies Elective (2)",
    level: 3,
    semester: 2,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },


];

const FOFall = [
  // Genreal
  {
    code: "ISM 411",
    name: "Web App Development",
    level: 4,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",

    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
    
  },

  {
    code: "NTM 412",
    name: "Cloud Computing",
    level: 4,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",

    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
    
  },
  {
    code: "ISM 413",
    name: "Database Manag. Sys. (2)",
    level: 4,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",

    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
    
  },
  {
    code: "FRM 416",
    name: "Project (1)",
    level: 4,
    semester: 1,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",

    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
    
  },
  // CS 
  {
    code: "CSM 414",
    name: "Software Engineering (2)",
    level: 4,
    semester: 1,
    program: "CS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "CSE 415",
    name: "Computer Science Elective (3)",
    level: 4,
    semester: 1,
    program: "CS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },

  // IS
  {
    name: "Business Intelligence",
    code: "ISM 412",
    level: 4,
    semester: 1,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    name: "E-Commerce",
    code: "ISM 414",
    level: 4,
    semester: 1,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "ISE 415",
    name: "nformation Systems Elective (3)",
    level: 4,
    semester: 1,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  //AI
  {
    code: "AIM 413",
    name: "Embedded systems",
    level: 4,
    semester: 1,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
  {
    code: "AIM 414",
    name: "Intelligent Autonomous Systems",
    level: 4,
    semester: 1,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "AIM 412",
    name: "Machine Learning",
    level: 4,
    semester: 1,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "AIM 411",
    name: "Data Mining and Analytics ",
    level: 4,
    semester: 1,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "AIM 415",
    name: "Artificial Intelligence Elective 3",
    level: 4,
    semester: 1,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },

  //Network Technologies
  {
    code: "NTM 413",
    name: "System Administration (1)",
    level: 4,
    semester: 1,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "NTM 414",
    name: "Wireless System Administration",
    level: 4,
    semester: 1,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "NTE 415",
    name: "Networking Technologies Elective (3)",
    level: 4,
    semester: 1,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },


];
const FOSpring = [
  // Genreal
  {
    code: "URM 421",
    name: "Communication Skills",
    level: 4,
    semester: 2,
    program: "general",
    credit_hours: "2",
    MT: "20",
    ClassWork: "20",

    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
    
  },

  {
    code: "NTM 422 ",
    name: "Internet of Things",
    level: 4,
    semester: 2,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",

    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
    
  },
  {
    code: "CSM 424",
    name: "Parallel Programming",
    level: 4,
    semester: 2,
    program: "general",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",

    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
    
  },
  {
    code: "FRM 426",
    name: "Project (2)",
    level: 4,
    semester: 2,
    program: "general",
    credit_hours: "0",
    MT: "0",
    ClassWork: "0",

    FinalWritten: "0",
    Lab: "0",
    byLaw: "2",
    
  },
  // CS 
  {
    code: "CSM 423",
    name: "Human Comp. Inter",
    level: 4,
    semester: 2,
    program: "CS",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "CSE 425",
    name: "Computer Science Elective (4)",
    level: 4,
    semester: 2,
    program: "CS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },

  // IS
  {
    name: "Information Security",
    code: "ISM 422",
    level: 4,
    semester: 2,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },

  {
    name: "Big Data",
    code: "ISM 423",
    level: 4,
    semester: 2,
    program: "IS",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    name: "Knowledge Management",
    code: "ISM 424",
    level: 4,
    semester: 2,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "FRM 429",
    name: "nformation Systems Elective (4)",
    level: 4,
    semester: 2,
    program: "IS",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  //AI
  {
    code: "AIM 422",
    name: "Natural Language Processing",
    level: 4,
    semester: 2,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },
 
  {
    code: "AIM 423",
    name: "Deep Learning",
    level: 4,
    semester: 2,
    program: "AI",
    credit_hours: "4",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },

  {
    code: "AIE 425",
    name: "Artificial Intelligence Elective (4)",
    level: 4,
    semester: 2,
    program: "AI",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "60",
    Lab: "0",
    byLaw: "2",
  },

  //Network Technologies
  {
    code: "NTM 423",
    name: "System Administration (2)",
    level: 4,
    semester: 2,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "NTM 424",
    name: "Mobile Networks",
    level: 4,
    semester: 2,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },
  {
    code: "NTE 425",
    name: "Networking Technologies Elective (4)",
    level: 4,
    semester: 2,
    program: "NT",
    credit_hours: "3",
    MT: "20",
    ClassWork: "20",
    FinalWritten: "40",
    Lab: "20",
    byLaw: "2",
  },


];


function addCheckedProperty(arr) {
  return arr.map(item => ({
      ...item,
      Checked: false
  }));
}

export const processedCourses = addCheckedProperty([...FFall , ...FSpring , ...SFall , ...SSpring , ...TFall , ...TSpring , ...FOSpring , ...FOFall]);

// console.log(processCourses);

function hasDuplicateByCode(arr) {
  const seenCodes = new Set();
  for (const item of arr) {
      if (seenCodes.has(item.code)) {
        console.log(item)
          return true; // Duplicate found
      }
      seenCodes.add(item.code);
  }
  return false; // No duplicates found
}
console.log("XXXXXXXXXXXXX")
console.log(hasDuplicateByCode([...FFall , ...FSpring , ...SFall , ...SSpring , ...TFall , ...TSpring , ...FOSpring , ...FOFall]))
console.log("XXXXXXXXXXXXX")